command_timeout = 1000

[c]
disabled=true

[cmake]
disabled = true

[git_status]
disabled=false
conflicted = "ïƒ¬"
modified = "ï…‹"
stashed = "âš¡ï¸"
staged = "ïƒ¾"
renamed = "ï‘š"
untracked = "ï™"
ahead = "â‡¡"
behind = "â‡£"
style = 'dimmed underline'

#stashed = "\uE0A0"

[git_metrics]
disabled=false
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_commit]
commit_hash_length = 4
tag_symbol = 'ğŸ”– '

